-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.achievements (
  id text NOT NULL,
  name text NOT NULL,
  description text NOT NULL,
  category USER-DEFINED NOT NULL,
  tier USER-DEFINED NOT NULL,
  icon text NOT NULL,
  points integer DEFAULT 0,
  requirement_value integer DEFAULT 1,
  is_secret boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT achievements_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admin_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  role USER-DEFINED NOT NULL,
  permission text NOT NULL,
  CONSTRAINT admin_permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admin_users (
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'moderator'::admin_role,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_users_pkey PRIMARY KEY (user_id),
  CONSTRAINT admin_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.appeals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  moderation_case_id uuid NOT NULL,
  statement text NOT NULL,
  evidence_urls ARRAY,
  evidence_storage_path text,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::appeal_status,
  assigned_admin_id uuid,
  outcome_notes text,
  decided_at timestamp with time zone,
  roocoin_at_stake numeric DEFAULT 0,
  roocoin_refunded boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT appeals_pkey PRIMARY KEY (id),
  CONSTRAINT appeals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT appeals_moderation_case_id_fkey FOREIGN KEY (moderation_case_id) REFERENCES public.moderation_cases(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_user_id uuid,
  actor_role text,
  actor_ip inet,
  actor_user_agent text,
  action text NOT NULL,
  action_category text,
  target_type text,
  target_id uuid,
  status text NOT NULL DEFAULT 'success'::text CHECK (status = ANY (ARRAY['success'::text, 'failed'::text, 'partial'::text])),
  error_message text,
  old_values jsonb,
  new_values jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.background_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_type text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'queued'::job_status,
  priority text NOT NULL DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'critical'::text])),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  result jsonb,
  scheduled_for timestamp with time zone DEFAULT now(),
  max_attempts integer NOT NULL DEFAULT 3,
  attempt_count integer NOT NULL DEFAULT 0,
  started_at timestamp with time zone,
  finished_at timestamp with time zone,
  error_message text,
  locked_by text,
  locked_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT background_jobs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.blocks (
  blocker_id uuid NOT NULL,
  blocked_id uuid NOT NULL,
  reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT blocks_pkey PRIMARY KEY (blocker_id, blocked_id),
  CONSTRAINT blocks_blocker_id_fkey FOREIGN KEY (blocker_id) REFERENCES public.profiles(user_id),
  CONSTRAINT blocks_blocked_id_fkey FOREIGN KEY (blocked_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.bookmarks (
  user_id uuid NOT NULL,
  post_id uuid NOT NULL,
  collection text DEFAULT 'default'::text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bookmarks_pkey PRIMARY KEY (user_id, post_id),
  CONSTRAINT bookmarks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT bookmarks_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id)
);
CREATE TABLE public.challenge_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  challenge_id uuid NOT NULL,
  post_id uuid NOT NULL,
  user_id uuid NOT NULL,
  vote_count integer DEFAULT 0,
  rank integer,
  prize_won_rc bigint DEFAULT 0,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT challenge_entries_pkey PRIMARY KEY (id),
  CONSTRAINT challenge_entries_challenge_id_fkey FOREIGN KEY (challenge_id) REFERENCES public.challenges(id),
  CONSTRAINT challenge_entries_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT challenge_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.challenge_votes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  challenge_id uuid NOT NULL,
  entry_id uuid NOT NULL,
  voter_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT challenge_votes_pkey PRIMARY KEY (id),
  CONSTRAINT challenge_votes_challenge_id_fkey FOREIGN KEY (challenge_id) REFERENCES public.challenges(id),
  CONSTRAINT challenge_votes_entry_id_fkey FOREIGN KEY (entry_id) REFERENCES public.challenge_entries(id),
  CONSTRAINT challenge_votes_voter_id_fkey FOREIGN KEY (voter_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.challenges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  rules text,
  cover_image_url text,
  starts_at timestamp with time zone NOT NULL,
  ends_at timestamp with time zone NOT NULL,
  voting_ends_at timestamp with time zone,
  prize_pool_rc bigint DEFAULT 0,
  first_prize_rc bigint DEFAULT 0,
  second_prize_rc bigint DEFAULT 0,
  third_prize_rc bigint DEFAULT 0,
  required_hashtag text NOT NULL,
  min_human_score integer DEFAULT 70,
  require_verification boolean DEFAULT false,
  entry_count integer DEFAULT 0,
  vote_count integer DEFAULT 0,
  status USER-DEFINED DEFAULT 'draft'::challenge_status,
  is_official boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT challenges_pkey PRIMARY KEY (id),
  CONSTRAINT challenges_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.circle_invites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  circle_id uuid NOT NULL,
  invited_by uuid NOT NULL,
  invited_user_id uuid,
  invite_code text UNIQUE,
  max_uses integer,
  use_count integer DEFAULT 0,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT circle_invites_pkey PRIMARY KEY (id),
  CONSTRAINT circle_invites_circle_id_fkey FOREIGN KEY (circle_id) REFERENCES public.trust_circles(id),
  CONSTRAINT circle_invites_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.profiles(user_id),
  CONSTRAINT circle_invites_invited_user_id_fkey FOREIGN KEY (invited_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.circle_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  circle_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role USER-DEFINED DEFAULT 'member'::circle_member_role,
  posts_contributed integer DEFAULT 0,
  trust_contribution numeric DEFAULT 0,
  joined_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT circle_members_pkey PRIMARY KEY (id),
  CONSTRAINT circle_members_circle_id_fkey FOREIGN KEY (circle_id) REFERENCES public.trust_circles(id),
  CONSTRAINT circle_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.circle_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  circle_id uuid NOT NULL,
  post_id uuid NOT NULL,
  shared_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT circle_posts_pkey PRIMARY KEY (id),
  CONSTRAINT circle_posts_circle_id_fkey FOREIGN KEY (circle_id) REFERENCES public.trust_circles(id),
  CONSTRAINT circle_posts_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT circle_posts_shared_by_fkey FOREIGN KEY (shared_by) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.collectible_owners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collectible_id uuid NOT NULL,
  owner_id uuid NOT NULL,
  edition_number integer NOT NULL,
  acquired_at timestamp with time zone NOT NULL DEFAULT now(),
  acquisition_type text CHECK (acquisition_type = ANY (ARRAY['mint'::text, 'purchase'::text, 'gift'::text, 'airdrop'::text])),
  acquisition_price_rc bigint,
  is_for_sale boolean DEFAULT false,
  sale_price_rc bigint,
  listed_at timestamp with time zone,
  CONSTRAINT collectible_owners_pkey PRIMARY KEY (id),
  CONSTRAINT collectible_owners_collectible_id_fkey FOREIGN KEY (collectible_id) REFERENCES public.collectibles(id),
  CONSTRAINT collectible_owners_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.collectible_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collectible_id uuid NOT NULL,
  edition_number integer NOT NULL,
  seller_id uuid,
  buyer_id uuid NOT NULL,
  price_rc bigint NOT NULL,
  royalty_rc bigint DEFAULT 0,
  platform_fee_rc bigint DEFAULT 0,
  tx_type text CHECK (tx_type = ANY (ARRAY['mint'::text, 'sale'::text, 'gift'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT collectible_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT collectible_transactions_collectible_id_fkey FOREIGN KEY (collectible_id) REFERENCES public.collectibles(id),
  CONSTRAINT collectible_transactions_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.profiles(user_id),
  CONSTRAINT collectible_transactions_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.collectibles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL,
  creator_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  rarity USER-DEFINED NOT NULL,
  edition_number integer NOT NULL,
  max_editions integer NOT NULL,
  mint_price_rc bigint NOT NULL,
  resale_royalty_percent numeric DEFAULT 5.0,
  minted_count integer DEFAULT 0,
  floor_price_rc bigint,
  last_sale_price_rc bigint,
  metadata jsonb DEFAULT '{}'::jsonb,
  is_mintable boolean DEFAULT true,
  minted_out_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT collectibles_pkey PRIMARY KEY (id),
  CONSTRAINT collectibles_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT collectibles_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.comment_reactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  comment_id uuid NOT NULL,
  user_id uuid NOT NULL,
  reaction_type text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT comment_reactions_pkey PRIMARY KEY (id),
  CONSTRAINT comment_reactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT comment_reactions_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES public.comments(id)
);
CREATE TABLE public.comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL,
  author_id uuid NOT NULL,
  parent_comment_id uuid,
  body text NOT NULL CHECK (char_length(body) <= 2000),
  status USER-DEFINED NOT NULL DEFAULT 'published'::comment_status,
  ai_score numeric CHECK (ai_score >= 0::numeric AND ai_score <= 100::numeric),
  likes_count integer NOT NULL DEFAULT 0,
  replies_count integer NOT NULL DEFAULT 0,
  is_edited boolean NOT NULL DEFAULT false,
  edited_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  media_url text,
  media_type text,
  ai_score_status text DEFAULT 'pass'::text CHECK (ai_score_status = ANY (ARRAY['pass'::text, 'review'::text, 'flagged'::text])),
  verification_session_id text,
  ai_metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT comments_pkey PRIMARY KEY (id),
  CONSTRAINT comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.profiles(user_id),
  CONSTRAINT comments_parent_comment_id_fkey FOREIGN KEY (parent_comment_id) REFERENCES public.comments(id)
);
CREATE TABLE public.content_translations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_type character varying NOT NULL CHECK (source_type::text = ANY (ARRAY['post'::character varying, 'comment'::character varying, 'story'::character varying, 'message'::character varying, 'bio'::character varying]::text[])),
  source_id uuid NOT NULL,
  source_language character varying NOT NULL,
  target_language character varying NOT NULL,
  original_text text NOT NULL,
  translated_text text NOT NULL,
  translation_provider character varying DEFAULT 'google'::character varying,
  confidence_score numeric,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '30 days'::interval),
  CONSTRAINT content_translations_pkey PRIMARY KEY (id),
  CONSTRAINT content_translations_target_language_fkey FOREIGN KEY (target_language) REFERENCES public.supported_languages(code)
);
CREATE TABLE public.creator_tiers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  tier USER-DEFINED NOT NULL,
  price_rc_monthly bigint NOT NULL,
  price_rc_yearly bigint,
  benefits jsonb DEFAULT '[]'::jsonb,
  subscriber_count integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT creator_tiers_pkey PRIMARY KEY (id),
  CONSTRAINT creator_tiers_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.detections (
  id uuid NOT NULL,
  content_hash character varying,
  content_type character varying NOT NULL,
  content_preview text,
  final_result character varying NOT NULL,
  final_confidence numeric NOT NULL,
  consensus_strength character varying NOT NULL,
  models_used jsonb NOT NULL DEFAULT '[]'::jsonb,
  model_results jsonb NOT NULL DEFAULT '[]'::jsonb,
  combined_evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
  final_rationale text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT detections_pkey PRIMARY KEY (id)
);
CREATE TABLE public.didit_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text NOT NULL UNIQUE,
  user_id uuid NOT NULL,
  session_url text NOT NULL,
  workflow_id text,
  vendor_data text,
  status text NOT NULL DEFAULT 'Not Started'::text CHECK (status = ANY (ARRAY['Not Started'::text, 'In Progress'::text, 'In Review'::text, 'Approved'::text, 'Declined'::text, 'Abandoned'::text])),
  verification_result jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT didit_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT didit_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.dm_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  thread_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  body text NOT NULL CHECK (char_length(body) <= 5000),
  status USER-DEFINED NOT NULL DEFAULT 'sent'::message_status,
  reply_to_id uuid,
  media_url text,
  media_type USER-DEFINED,
  is_edited boolean NOT NULL DEFAULT false,
  edited_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  ai_score numeric CHECK (ai_score >= 0::numeric AND ai_score <= 100::numeric),
  ai_score_status text DEFAULT 'pass'::text CHECK (ai_score_status = ANY (ARRAY['pass'::text, 'review'::text, 'flagged'::text])),
  ai_metadata jsonb DEFAULT '{}'::jsonb,
  verification_session_id text,
  delivered_at timestamp with time zone,
  read_at timestamp with time zone,
  CONSTRAINT dm_messages_pkey PRIMARY KEY (id),
  CONSTRAINT dm_messages_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.dm_threads(id),
  CONSTRAINT dm_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(user_id),
  CONSTRAINT dm_messages_reply_to_id_fkey FOREIGN KEY (reply_to_id) REFERENCES public.dm_messages(id)
);
CREATE TABLE public.dm_participants (
  thread_id uuid NOT NULL,
  user_id uuid NOT NULL,
  is_muted boolean NOT NULL DEFAULT false,
  is_archived boolean NOT NULL DEFAULT false,
  nickname text,
  last_read_at timestamp with time zone,
  unread_count integer NOT NULL DEFAULT 0,
  is_admin boolean NOT NULL DEFAULT false,
  joined_at timestamp with time zone NOT NULL DEFAULT now(),
  left_at timestamp with time zone,
  CONSTRAINT dm_participants_pkey PRIMARY KEY (thread_id, user_id),
  CONSTRAINT dm_participants_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.dm_threads(id),
  CONSTRAINT dm_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.dm_read_receipts (
  message_id uuid NOT NULL,
  user_id uuid NOT NULL,
  read_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT dm_read_receipts_pkey PRIMARY KEY (message_id, user_id),
  CONSTRAINT dm_read_receipts_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.dm_messages(id),
  CONSTRAINT dm_read_receipts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.dm_threads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_by uuid NOT NULL,
  is_group boolean NOT NULL DEFAULT false,
  group_name text,
  group_avatar_url text,
  last_message_at timestamp with time zone,
  last_message_preview text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT dm_threads_pkey PRIMARY KEY (id),
  CONSTRAINT dm_threads_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.faq (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  question text NOT NULL,
  answer text NOT NULL,
  category text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_published boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT faq_pkey PRIMARY KEY (id)
);
CREATE TABLE public.feedback (
  id bigint NOT NULL DEFAULT nextval('feedback_id_seq'::regclass),
  detection_id uuid,
  correct_result character varying NOT NULL,
  original_result character varying NOT NULL,
  was_correct boolean NOT NULL,
  feedback_notes text,
  source character varying DEFAULT 'user'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT feedback_pkey PRIMARY KEY (id),
  CONSTRAINT feedback_detection_id_fkey FOREIGN KEY (detection_id) REFERENCES public.detections(id)
);
CREATE TABLE public.follows (
  follower_id uuid NOT NULL,
  following_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT follows_pkey PRIMARY KEY (follower_id, following_id),
  CONSTRAINT follows_follower_id_fkey FOREIGN KEY (follower_id) REFERENCES public.profiles(user_id),
  CONSTRAINT follows_following_id_fkey FOREIGN KEY (following_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.help_articles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  content text NOT NULL,
  category text NOT NULL,
  meta_description text,
  keywords ARRAY,
  is_published boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT help_articles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.human_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  method USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::verification_status,
  phone_number_hash text,
  document_type text,
  evidence_storage_path text,
  liveness_score numeric,
  document_match_score numeric,
  reviewer_admin_id uuid,
  reviewer_notes text,
  rejection_reason text,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  reviewed_at timestamp with time zone,
  expires_at timestamp with time zone,
  attempt_number integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT human_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT human_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.kyc_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  verification_id uuid NOT NULL,
  user_id uuid NOT NULL,
  document_type text NOT NULL CHECK (document_type = ANY (ARRAY['passport'::text, 'drivers_license'::text, 'national_id'::text, 'utility_bill'::text, 'selfie'::text, 'selfie_with_doc'::text])),
  document_side text CHECK (document_side = ANY (ARRAY['front'::text, 'back'::text, 'single'::text])),
  storage_path text NOT NULL,
  ai_detection_score numeric CHECK (ai_detection_score >= 0::numeric AND ai_detection_score <= 100::numeric),
  ai_detection_status text CHECK (ai_detection_status = ANY (ARRAY['pass'::text, 'review'::text, 'flagged'::text])),
  validation_status text DEFAULT 'pending'::text CHECK (validation_status = ANY (ARRAY['pending'::text, 'valid'::text, 'invalid'::text, 'expired'::text, 'ai_rejected'::text])),
  rejection_reason text,
  extracted_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT kyc_documents_pkey PRIMARY KEY (id),
  CONSTRAINT kyc_documents_verification_id_fkey FOREIGN KEY (verification_id) REFERENCES public.human_verifications(id),
  CONSTRAINT kyc_documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.learned_patterns (
  id bigint NOT NULL DEFAULT nextval('learned_patterns_id_seq'::regclass),
  pattern_type character varying NOT NULL,
  pattern_text character varying NOT NULL,
  content_type character varying NOT NULL,
  result_association character varying NOT NULL,
  frequency integer DEFAULT 1,
  accuracy_score numeric DEFAULT 0.50,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT learned_patterns_pkey PRIMARY KEY (id)
);
CREATE TABLE public.legal_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type text NOT NULL UNIQUE CHECK (type = ANY (ARRAY['terms'::text, 'privacy'::text, 'cookies'::text, 'content_policy'::text, 'community_guidelines'::text])),
  title text NOT NULL,
  content text NOT NULL,
  version text NOT NULL,
  effective_date date NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT legal_documents_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mentions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid,
  comment_id uuid,
  mentioned_user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mentions_pkey PRIMARY KEY (id),
  CONSTRAINT mentions_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT mentions_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES public.comments(id),
  CONSTRAINT mentions_mentioned_user_id_fkey FOREIGN KEY (mentioned_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.model_accuracy (
  model_name character varying NOT NULL,
  total_predictions integer DEFAULT 0,
  correct_predictions integer DEFAULT 0,
  accuracy numeric DEFAULT 0.0000,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT model_accuracy_pkey PRIMARY KEY (model_name)
);
CREATE TABLE public.moderation_cases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid,
  comment_id uuid,
  reported_user_id uuid,
  reason USER-DEFINED NOT NULL,
  source text NOT NULL DEFAULT 'ai'::text CHECK (source = ANY (ARRAY['ai'::text, 'user_report'::text, 'system'::text, 'admin'::text])),
  description text,
  ai_confidence numeric CHECK (ai_confidence >= 0::numeric AND ai_confidence <= 100::numeric),
  ai_model text,
  ai_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::moderation_status,
  priority text NOT NULL DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  assigned_admin_id uuid,
  decision USER-DEFINED,
  decision_notes text,
  decided_at timestamp with time zone,
  escalated_to uuid,
  escalation_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  media_url text,
  story_id uuid,
  message_id uuid,
  CONSTRAINT moderation_cases_pkey PRIMARY KEY (id),
  CONSTRAINT moderation_cases_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT moderation_cases_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES public.comments(id),
  CONSTRAINT moderation_cases_reported_user_id_fkey FOREIGN KEY (reported_user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT moderation_cases_story_id_fkey FOREIGN KEY (story_id) REFERENCES public.stories(id),
  CONSTRAINT moderation_cases_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.dm_messages(id)
);
CREATE TABLE public.mutes (
  muter_id uuid NOT NULL,
  muted_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mutes_pkey PRIMARY KEY (muter_id, muted_id),
  CONSTRAINT mutes_muter_id_fkey FOREIGN KEY (muter_id) REFERENCES public.profiles(user_id),
  CONSTRAINT mutes_muted_id_fkey FOREIGN KEY (muted_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.notification_preferences (
  user_id uuid NOT NULL,
  email_enabled boolean NOT NULL DEFAULT true,
  email_follows boolean NOT NULL DEFAULT true,
  email_comments boolean NOT NULL DEFAULT true,
  email_mentions boolean NOT NULL DEFAULT true,
  email_messages boolean NOT NULL DEFAULT true,
  email_marketing boolean NOT NULL DEFAULT false,
  email_digest_frequency text DEFAULT 'daily'::text CHECK (email_digest_frequency = ANY (ARRAY['realtime'::text, 'daily'::text, 'weekly'::text, 'never'::text])),
  push_enabled boolean NOT NULL DEFAULT true,
  push_follows boolean NOT NULL DEFAULT true,
  push_comments boolean NOT NULL DEFAULT true,
  push_reactions boolean NOT NULL DEFAULT true,
  push_mentions boolean NOT NULL DEFAULT true,
  push_messages boolean NOT NULL DEFAULT true,
  push_moderation boolean NOT NULL DEFAULT true,
  push_roocoin boolean NOT NULL DEFAULT true,
  push_staking boolean NOT NULL DEFAULT true,
  inapp_follows boolean NOT NULL DEFAULT true,
  inapp_comments boolean NOT NULL DEFAULT true,
  inapp_reactions boolean NOT NULL DEFAULT true,
  inapp_mentions boolean NOT NULL DEFAULT true,
  inapp_reposts boolean NOT NULL DEFAULT true,
  quiet_hours_enabled boolean NOT NULL DEFAULT false,
  quiet_hours_start time without time zone,
  quiet_hours_end time without time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (user_id),
  CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type USER-DEFINED NOT NULL,
  title text,
  body text,
  icon text,
  icon_color text,
  image_url text,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  actor_id uuid,
  post_id uuid,
  comment_id uuid,
  thread_id uuid,
  appeal_id uuid,
  moderation_case_id uuid,
  transaction_id uuid,
  action_url text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  story_id uuid,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT notifications_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.profiles(user_id),
  CONSTRAINT notifications_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT notifications_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES public.comments(id),
  CONSTRAINT notifications_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.dm_threads(id)
);
CREATE TABLE public.platform_config (
  id smallint NOT NULL DEFAULT 1 CHECK (id = 1),
  allow_new_signups boolean NOT NULL DEFAULT true,
  require_email_verification boolean NOT NULL DEFAULT true,
  require_human_verification boolean NOT NULL DEFAULT false,
  maintenance_mode boolean NOT NULL DEFAULT false,
  maintenance_message text,
  roocoin_trading_enabled boolean NOT NULL DEFAULT true,
  ai_flag_threshold numeric NOT NULL DEFAULT 85,
  auto_ban_threshold numeric NOT NULL DEFAULT 98,
  max_post_length integer NOT NULL DEFAULT 10000,
  max_comment_length integer NOT NULL DEFAULT 2000,
  max_bio_length integer NOT NULL DEFAULT 500,
  max_media_per_post integer NOT NULL DEFAULT 10,
  max_tags_per_post integer NOT NULL DEFAULT 10,
  default_publish_fee_rc numeric NOT NULL DEFAULT 0,
  default_staking_apy_percent numeric NOT NULL DEFAULT 5,
  new_user_bonus_rc numeric NOT NULL DEFAULT 100,
  posts_per_day_limit integer NOT NULL DEFAULT 50,
  comments_per_hour_limit integer NOT NULL DEFAULT 100,
  messages_per_minute_limit integer NOT NULL DEFAULT 30,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  platform_name text DEFAULT 'Rooverse'::text,
  platform_logo_url text,
  admin_contact_email text,
  platform_description text,
  tos_url text,
  privacy_policy_url text,
  min_password_length integer NOT NULL DEFAULT 8,
  username_min_length integer NOT NULL DEFAULT 3,
  username_max_length integer NOT NULL DEFAULT 20,
  max_login_attempts integer NOT NULL DEFAULT 5,
  account_deletion_grace_period_days integer NOT NULL DEFAULT 30,
  max_upload_size_mb numeric NOT NULL DEFAULT 10,
  max_images_per_post integer NOT NULL DEFAULT 5,
  max_video_duration_seconds integer NOT NULL DEFAULT 60,
  nsfw_handling text NOT NULL DEFAULT 'blur'::text CHECK (nsfw_handling = ANY (ARRAY['block'::text, 'blur'::text, 'allow'::text])),
  enable_stories boolean NOT NULL DEFAULT true,
  enable_challenges boolean NOT NULL DEFAULT true,
  enable_trust_circles boolean NOT NULL DEFAULT true,
  enable_collectibles boolean NOT NULL DEFAULT true,
  email_notifications_enabled boolean NOT NULL DEFAULT true,
  push_notifications_enabled boolean NOT NULL DEFAULT true,
  notification_batching_interval_minutes integer NOT NULL DEFAULT 5,
  api_rate_limit_per_minute integer NOT NULL DEFAULT 60,
  post_rate_limit_per_hour integer NOT NULL DEFAULT 10,
  comment_rate_limit_per_hour integer NOT NULL DEFAULT 30,
  dm_rate_limit_per_hour integer NOT NULL DEFAULT 20,
  mobile_app_latest_version text NOT NULL DEFAULT '1.0.0'::text,
  CONSTRAINT platform_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.poll_options (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  poll_id uuid NOT NULL,
  option_text text NOT NULL,
  vote_count integer DEFAULT 0,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT poll_options_pkey PRIMARY KEY (id),
  CONSTRAINT poll_options_poll_id_fkey FOREIGN KEY (poll_id) REFERENCES public.polls(id)
);
CREATE TABLE public.poll_votes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  poll_id uuid NOT NULL,
  option_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT poll_votes_pkey PRIMARY KEY (id),
  CONSTRAINT poll_votes_poll_id_fkey FOREIGN KEY (poll_id) REFERENCES public.polls(id),
  CONSTRAINT poll_votes_option_id_fkey FOREIGN KEY (option_id) REFERENCES public.poll_options(id),
  CONSTRAINT poll_votes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.polls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL UNIQUE,
  question text NOT NULL,
  ends_at timestamp with time zone,
  allow_multiple boolean DEFAULT false,
  is_anonymous boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT polls_pkey PRIMARY KEY (id),
  CONSTRAINT polls_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id)
);
CREATE TABLE public.post_drafts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text,
  body text NOT NULL DEFAULT ''::text,
  tags ARRAY,
  media_paths ARRAY,
  last_saved_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT post_drafts_pkey PRIMARY KEY (id),
  CONSTRAINT post_drafts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.post_media (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL,
  media_type USER-DEFINED NOT NULL,
  storage_path text NOT NULL,
  storage_bucket text NOT NULL DEFAULT 'post-media'::text,
  original_filename text,
  mime_type text,
  file_size integer,
  width integer,
  height integer,
  duration_seconds numeric,
  thumbnail_path text,
  is_processed boolean NOT NULL DEFAULT false,
  processing_error text,
  alt_text text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT post_media_pkey PRIMARY KEY (id),
  CONSTRAINT post_media_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id)
);
CREATE TABLE public.post_tags (
  post_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT post_tags_pkey PRIMARY KEY (post_id, tag_id),
  CONSTRAINT post_tags_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT post_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id)
);
CREATE TABLE public.post_views (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL,
  user_id uuid,
  session_id text,
  ip_hash text,
  referrer text,
  source text,
  viewed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT post_views_pkey PRIMARY KEY (id),
  CONSTRAINT post_views_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT post_views_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  author_id uuid NOT NULL,
  title text CHECK (title IS NULL OR char_length(title) <= 300),
  body text NOT NULL DEFAULT ''::text CHECK (char_length(body) <= 10000),
  body_format text NOT NULL DEFAULT 'markdown'::text CHECK (body_format = ANY (ARRAY['plain'::text, 'markdown'::text, 'html'::text])),
  status USER-DEFINED NOT NULL DEFAULT 'draft'::post_status,
  visibility USER-DEFINED NOT NULL DEFAULT 'public'::privacy_level,
  human_certified boolean NOT NULL DEFAULT false,
  ai_score numeric CHECK (ai_score >= 0::numeric AND ai_score <= 100::numeric),
  ai_score_status text CHECK (ai_score_status = ANY (ARRAY['pass'::text, 'review'::text, 'flagged'::text])),
  authenticity_notes text,
  verification_method text,
  verification_session_id text,
  is_sensitive boolean NOT NULL DEFAULT false,
  sensitive_reason USER-DEFINED DEFAULT 'none'::sensitivity_reason,
  scheduled_at timestamp with time zone,
  published_at timestamp with time zone,
  likes_count integer NOT NULL DEFAULT 0,
  comments_count integer NOT NULL DEFAULT 0,
  reposts_count integer NOT NULL DEFAULT 0,
  views_count integer NOT NULL DEFAULT 0,
  shares_count integer NOT NULL DEFAULT 0,
  publish_fee_rc numeric NOT NULL DEFAULT 0,
  total_tips_rc numeric NOT NULL DEFAULT 0,
  edit_count integer NOT NULL DEFAULT 0,
  last_edited_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  location text,
  ai_metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT posts_pkey PRIMARY KEY (id),
  CONSTRAINT posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.profile_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  platform text NOT NULL,
  label text NOT NULL,
  url text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_verified boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profile_links_pkey PRIMARY KEY (id),
  CONSTRAINT profile_links_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.profiles (
  user_id uuid NOT NULL,
  username text NOT NULL UNIQUE CHECK (char_length(username) >= 3 AND char_length(username) <= 32 AND username ~ '^[a-zA-Z0-9_]+$'::text),
  display_name text NOT NULL DEFAULT ''::text,
  bio text NOT NULL DEFAULT ''::text CHECK (char_length(bio) <= 500),
  avatar_url text,
  cover_image_url text,
  website_url text,
  location text,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::user_status,
  verified_human USER-DEFINED NOT NULL DEFAULT 'unverified'::verification_status,
  verification_method USER-DEFINED,
  verified_at timestamp with time zone,
  trust_score numeric NOT NULL DEFAULT 0 CHECK (trust_score >= 0::numeric AND trust_score <= 100::numeric),
  ml_score numeric NOT NULL DEFAULT 50 CHECK (ml_score >= 0::numeric AND ml_score <= 100::numeric),
  followers_count integer NOT NULL DEFAULT 0,
  following_count integer NOT NULL DEFAULT 0,
  posts_count integer NOT NULL DEFAULT 0,
  profile_privacy USER-DEFINED NOT NULL DEFAULT 'public'::privacy_level,
  show_activity boolean NOT NULL DEFAULT true,
  show_online_status boolean NOT NULL DEFAULT true,
  allow_messages_from USER-DEFINED NOT NULL DEFAULT 'public'::privacy_level,
  language text NOT NULL DEFAULT 'en'::text,
  timezone text DEFAULT 'UTC'::text,
  last_active_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  interests jsonb DEFAULT '[]'::jsonb,
  phone_number text,
  posts_visibility text NOT NULL DEFAULT 'everyone'::text CHECK (posts_visibility = ANY (ARRAY['everyone'::text, 'followers'::text, 'private'::text])),
  comments_visibility text NOT NULL DEFAULT 'everyone'::text CHECK (comments_visibility = ANY (ARRAY['everyone'::text, 'followers'::text, 'private'::text])),
  messages_visibility text NOT NULL DEFAULT 'everyone'::text CHECK (messages_visibility = ANY (ARRAY['everyone'::text, 'followers'::text, 'private'::text])),
  birth_date date,
  avatar_ai_checked boolean DEFAULT false,
  avatar_ai_score numeric CHECK (avatar_ai_score >= 0::numeric AND avatar_ai_score <= 100::numeric),
  CONSTRAINT profiles_pkey PRIMARY KEY (user_id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.push_notification_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  notification_id uuid,
  user_id uuid NOT NULL,
  token_id uuid,
  status text NOT NULL CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'delivered'::text, 'failed'::text, 'clicked'::text, 'dismissed'::text])),
  error_message text,
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  clicked_at timestamp with time zone,
  dismissed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT push_notification_logs_pkey PRIMARY KEY (id),
  CONSTRAINT push_notification_logs_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES public.notifications(id),
  CONSTRAINT push_notification_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT push_notification_logs_token_id_fkey FOREIGN KEY (token_id) REFERENCES public.push_tokens(id)
);
CREATE TABLE public.push_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  token text NOT NULL,
  device_id text NOT NULL,
  platform text NOT NULL DEFAULT 'web'::text CHECK (platform = ANY (ARRAY['web'::text, 'android'::text, 'ios'::text])),
  browser_name text,
  browser_version text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  last_active_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT push_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT push_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.reactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  post_id uuid,
  comment_id uuid,
  reaction_type USER-DEFINED NOT NULL DEFAULT 'like'::reaction_type,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  story_id uuid,
  CONSTRAINT reactions_pkey PRIMARY KEY (id),
  CONSTRAINT reactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT reactions_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT reactions_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES public.comments(id),
  CONSTRAINT reactions_story_id_fkey FOREIGN KEY (story_id) REFERENCES public.stories(id)
);
CREATE TABLE public.referral_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  code text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT referral_codes_pkey PRIMARY KEY (id),
  CONSTRAINT referral_codes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  referrer_id uuid NOT NULL,
  referred_id uuid NOT NULL,
  referral_code_id uuid,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'verified'::character varying, 'rewarded'::character varying, 'rejected'::character varying, 'fraud_detected'::character varying]::text[])),
  registration_completed boolean DEFAULT false,
  email_verified boolean DEFAULT false,
  profile_completed boolean DEFAULT false,
  identity_verified boolean DEFAULT false,
  first_post_created boolean DEFAULT false,
  minimum_activity_reached boolean DEFAULT false,
  referrer_reward_amount numeric DEFAULT 0,
  referred_rewarded_at timestamp with time zone,
  referred_ip_address inet,
  referred_device_fingerprint character varying,
  fraud_score numeric DEFAULT 0 CHECK (fraud_score >= 0::numeric AND fraud_score <= 100::numeric),
  fraud_flags jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  verified_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT referrals_pkey PRIMARY KEY (id),
  CONSTRAINT referrals_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES public.profiles(user_id),
  CONSTRAINT referrals_referred_id_fkey FOREIGN KEY (referred_id) REFERENCES public.profiles(user_id),
  CONSTRAINT referrals_referral_code_id_fkey FOREIGN KEY (referral_code_id) REFERENCES public.referral_codes(id)
);
CREATE TABLE public.reposts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  post_id uuid NOT NULL,
  quote_text text CHECK (quote_text IS NULL OR char_length(quote_text) <= 500),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT reposts_pkey PRIMARY KEY (id),
  CONSTRAINT reposts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT reposts_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id)
);
CREATE TABLE public.roocoin_daily_rewards (
  user_id uuid NOT NULL,
  reward_date date NOT NULL,
  total_earned_rc numeric NOT NULL DEFAULT 0,
  breakdown jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT roocoin_daily_rewards_pkey PRIMARY KEY (user_id, reward_date),
  CONSTRAINT roocoin_daily_rewards_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.roocoin_reward_global_limits (
  id smallint NOT NULL DEFAULT 1 CHECK (id = 1),
  daily_cap numeric NOT NULL DEFAULT 50,
  CONSTRAINT roocoin_reward_global_limits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.roocoin_reward_limits (
  activity_type text NOT NULL,
  daily_cap numeric NOT NULL DEFAULT 0,
  cooldown_seconds integer NOT NULL DEFAULT 0,
  is_one_time boolean NOT NULL DEFAULT false,
  requires_verified boolean NOT NULL DEFAULT false,
  CONSTRAINT roocoin_reward_limits_pkey PRIMARY KEY (activity_type)
);
CREATE TABLE public.roocoin_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tx_type USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::roocoin_tx_status,
  from_user_id uuid,
  to_user_id uuid,
  amount_rc numeric NOT NULL CHECK (amount_rc >= 0::numeric),
  fee_rc numeric NOT NULL DEFAULT 0 CHECK (fee_rc >= 0::numeric),
  reference_post_id uuid,
  reference_comment_id uuid,
  memo text,
  tx_hash text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  failed_at timestamp with time zone,
  failure_reason text,
  CONSTRAINT roocoin_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT roocoin_transactions_from_user_id_fkey FOREIGN KEY (from_user_id) REFERENCES public.wallets(user_id),
  CONSTRAINT roocoin_transactions_to_user_id_fkey FOREIGN KEY (to_user_id) REFERENCES public.wallets(user_id),
  CONSTRAINT roocoin_transactions_reference_post_id_fkey FOREIGN KEY (reference_post_id) REFERENCES public.posts(id),
  CONSTRAINT roocoin_transactions_reference_comment_id_fkey FOREIGN KEY (reference_comment_id) REFERENCES public.comments(id)
);
CREATE TABLE public.search_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  query text NOT NULL,
  search_type text NOT NULL DEFAULT 'all'::text CHECK (search_type = ANY (ARRAY['all'::text, 'posts'::text, 'users'::text, 'tags'::text])),
  results_count integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT search_history_pkey PRIMARY KEY (id),
  CONSTRAINT search_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.staking_positions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  tier_id uuid,
  amount_rc numeric NOT NULL CHECK (amount_rc > 0::numeric),
  apy_percent numeric NOT NULL,
  lock_days integer NOT NULL DEFAULT 0,
  status USER-DEFINED NOT NULL DEFAULT 'active'::staking_status,
  total_rewards_rc numeric NOT NULL DEFAULT 0,
  last_reward_at timestamp with time zone,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  unlock_at timestamp with time zone,
  closed_at timestamp with time zone,
  early_withdrawal_fee_percent numeric DEFAULT 5,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT staking_positions_pkey PRIMARY KEY (id),
  CONSTRAINT staking_positions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.wallets(user_id),
  CONSTRAINT staking_positions_tier_id_fkey FOREIGN KEY (tier_id) REFERENCES public.staking_tiers(id)
);
CREATE TABLE public.staking_rewards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  position_id uuid NOT NULL,
  user_id uuid NOT NULL,
  transaction_id uuid,
  amount_rc numeric NOT NULL CHECK (amount_rc >= 0::numeric),
  period_start timestamp with time zone NOT NULL,
  period_end timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT staking_rewards_pkey PRIMARY KEY (id),
  CONSTRAINT staking_rewards_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.wallets(user_id),
  CONSTRAINT staking_rewards_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.staking_positions(id),
  CONSTRAINT staking_rewards_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.roocoin_transactions(id)
);
CREATE TABLE public.staking_tiers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  min_amount_rc numeric NOT NULL,
  max_amount_rc numeric,
  lock_days integer NOT NULL DEFAULT 0,
  apy_percent numeric NOT NULL,
  bonus_multiplier numeric NOT NULL DEFAULT 1.0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT staking_tiers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.stories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  media_url text,
  media_type text NOT NULL CHECK (media_type = ANY (ARRAY['image'::text, 'video'::text, 'text'::text])),
  caption text,
  background_color text,
  text_overlay text,
  text_position jsonb,
  view_count integer DEFAULT 0,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  ai_score numeric CHECK (ai_score >= 0::numeric AND ai_score <= 100::numeric),
  status text CHECK (status = ANY (ARRAY['pass'::text, 'review'::text, 'flagged'::text])),
  verification_session_id text,
  ai_metadata jsonb DEFAULT '{}'::jsonb,
  ai_score_status text CHECK (ai_score_status = ANY (ARRAY['pass'::text, 'review'::text, 'flagged'::text])),
  CONSTRAINT stories_pkey PRIMARY KEY (id),
  CONSTRAINT stories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.story_views (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  story_id uuid NOT NULL,
  viewer_id uuid NOT NULL,
  viewed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT story_views_pkey PRIMARY KEY (id),
  CONSTRAINT story_views_story_id_fkey FOREIGN KEY (story_id) REFERENCES public.stories(id),
  CONSTRAINT story_views_viewer_id_fkey FOREIGN KEY (viewer_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.streaks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  streak_type text NOT NULL,
  current_count integer DEFAULT 0,
  longest_count integer DEFAULT 0,
  last_activity_date date,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT streaks_pkey PRIMARY KEY (id),
  CONSTRAINT streaks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.subscriber_only_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL UNIQUE,
  creator_id uuid NOT NULL,
  min_tier USER-DEFINED NOT NULL,
  teaser_text text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT subscriber_only_posts_pkey PRIMARY KEY (id),
  CONSTRAINT subscriber_only_posts_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT subscriber_only_posts_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscriber_id uuid NOT NULL,
  creator_id uuid NOT NULL,
  tier_id uuid NOT NULL,
  price_paid_rc bigint NOT NULL,
  billing_period text CHECK (billing_period = ANY (ARRAY['monthly'::text, 'yearly'::text])),
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'cancelled'::text, 'expired'::text, 'paused'::text])),
  auto_renew boolean DEFAULT true,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  current_period_start timestamp with time zone NOT NULL DEFAULT now(),
  current_period_end timestamp with time zone NOT NULL,
  cancelled_at timestamp with time zone,
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_subscriber_id_fkey FOREIGN KEY (subscriber_id) REFERENCES public.profiles(user_id),
  CONSTRAINT subscriptions_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.profiles(user_id),
  CONSTRAINT subscriptions_tier_id_fkey FOREIGN KEY (tier_id) REFERENCES public.creator_tiers(id)
);
CREATE TABLE public.support_ticket_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  message text NOT NULL,
  is_staff boolean NOT NULL DEFAULT false,
  attachments jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT support_ticket_messages_pkey PRIMARY KEY (id),
  CONSTRAINT support_ticket_messages_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id),
  CONSTRAINT support_ticket_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subject text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['account'::text, 'content'::text, 'wallet'::text, 'technical'::text, 'verification'::text, 'other'::text])),
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'in_progress'::text, 'waiting_response'::text, 'resolved'::text, 'closed'::text])),
  assigned_to uuid,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT support_tickets_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.supported_languages (
  code character varying NOT NULL,
  name character varying NOT NULL,
  native_name character varying NOT NULL,
  direction character varying DEFAULT 'ltr'::character varying CHECK (direction::text = ANY (ARRAY['ltr'::character varying, 'rtl'::character varying]::text[])),
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT supported_languages_pkey PRIMARY KEY (code)
);
CREATE TABLE public.tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE CHECK (char_length(name) >= 1 AND char_length(name) <= 50 AND name ~ '^[a-zA-Z0-9_]+$'::text),
  slug text NOT NULL UNIQUE,
  description text,
  posts_count integer NOT NULL DEFAULT 0,
  trending_score numeric NOT NULL DEFAULT 0,
  is_featured boolean NOT NULL DEFAULT false,
  is_blocked boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tags_pkey PRIMARY KEY (id)
);
CREATE TABLE public.translation_strings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key character varying NOT NULL,
  language_code character varying NOT NULL,
  value text NOT NULL,
  context character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT translation_strings_pkey PRIMARY KEY (id),
  CONSTRAINT translation_strings_language_code_fkey FOREIGN KEY (language_code) REFERENCES public.supported_languages(code)
);
CREATE TABLE public.treasury_actions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_id uuid NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['mint'::text, 'burn'::text, 'freeze_global_trading'::text, 'unfreeze_global_trading'::text, 'adjust_user_balance'::text, 'freeze_user_wallet'::text, 'unfreeze_user_wallet'::text])),
  target_user_id uuid,
  amount_rc numeric,
  reason text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT treasury_actions_pkey PRIMARY KEY (id),
  CONSTRAINT treasury_actions_target_user_id_fkey FOREIGN KEY (target_user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.treasury_wallet (
  id smallint NOT NULL DEFAULT 1 CHECK (id = 1),
  balance_rc numeric NOT NULL DEFAULT 0,
  total_minted_rc numeric NOT NULL DEFAULT 0,
  total_burned_rc numeric NOT NULL DEFAULT 0,
  trading_frozen boolean NOT NULL DEFAULT false,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT treasury_wallet_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trending_topics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  topic_type text NOT NULL CHECK (topic_type = ANY (ARRAY['tag'::text, 'search'::text, 'user'::text])),
  topic_id uuid,
  topic_name text NOT NULL,
  post_count integer NOT NULL DEFAULT 0,
  engagement_count integer NOT NULL DEFAULT 0,
  velocity_score numeric NOT NULL DEFAULT 0,
  period text NOT NULL DEFAULT '24h'::text CHECK (period = ANY (ARRAY['1h'::text, '6h'::text, '24h'::text, '7d'::text, '30d'::text])),
  rank integer NOT NULL,
  calculated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trending_topics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trust_circles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  avatar_url text,
  cover_image_url text,
  privacy USER-DEFINED DEFAULT 'private'::circle_privacy,
  min_trust_score integer DEFAULT 50,
  require_verification boolean DEFAULT true,
  collective_trust_score numeric DEFAULT 0,
  member_count integer DEFAULT 0,
  post_count integer DEFAULT 0,
  created_by uuid NOT NULL,
  is_featured boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trust_circles_pkey PRIMARY KEY (id),
  CONSTRAINT trust_circles_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.trust_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  event_type text NOT NULL,
  delta numeric NOT NULL DEFAULT 0,
  new_score numeric NOT NULL,
  reason text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trust_events_pkey PRIMARY KEY (id),
  CONSTRAINT trust_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.two_factor_auth (
  user_id uuid NOT NULL,
  is_enabled boolean NOT NULL DEFAULT false,
  method text CHECK (method = ANY (ARRAY['totp'::text, 'sms'::text, 'email'::text])),
  totp_secret_encrypted text,
  backup_codes_hash ARRAY,
  backup_codes_used integer NOT NULL DEFAULT 0,
  recovery_email text,
  recovery_phone text,
  enabled_at timestamp with time zone,
  last_used_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT two_factor_auth_pkey PRIMARY KEY (user_id),
  CONSTRAINT two_factor_auth_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.user_achievements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  achievement_id text NOT NULL,
  progress integer DEFAULT 0,
  unlocked_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_achievements_pkey PRIMARY KEY (id),
  CONSTRAINT user_achievements_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT user_achievements_achievement_id_fkey FOREIGN KEY (achievement_id) REFERENCES public.achievements(id)
);
CREATE TABLE public.user_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  activity_type text NOT NULL CHECK (activity_type = ANY (ARRAY['login'::text, 'logout'::text, 'post'::text, 'comment'::text, 'like'::text, 'follow'::text, 'unfollow'::text, 'share'::text, 'bookmark'::text, 'story'::text, 'tip'::text, 'stake'::text, 'unstake'::text, 'reward'::text, 'transaction'::text, 'profile_update'::text, 'settings_change'::text, 'verification'::text, 'password_change'::text, 'email_change'::text])),
  target_type text CHECK (target_type = ANY (ARRAY['post'::text, 'comment'::text, 'user'::text, 'story'::text, 'wallet'::text, 'settings'::text])),
  target_id uuid,
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address text,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_activities_pkey PRIMARY KEY (id),
  CONSTRAINT user_activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.user_activity_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  session_id uuid,
  activity_type character varying NOT NULL,
  activity_category character varying,
  target_type character varying,
  target_id uuid,
  ip_address inet,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_activity_log_pkey PRIMARY KEY (id),
  CONSTRAINT user_activity_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT user_activity_log_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.user_sessions(id)
);
CREATE TABLE public.user_analytics_daily (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  date date NOT NULL,
  posts_created integer DEFAULT 0,
  comments_created integer DEFAULT 0,
  stories_created integer DEFAULT 0,
  likes_given integer DEFAULT 0,
  likes_received integer DEFAULT 0,
  comments_received integer DEFAULT 0,
  shares_given integer DEFAULT 0,
  shares_received integer DEFAULT 0,
  follows_given integer DEFAULT 0,
  follows_received integer DEFAULT 0,
  messages_sent integer DEFAULT 0,
  messages_received integer DEFAULT 0,
  transactions_count integer DEFAULT 0,
  roo_earned numeric DEFAULT 0,
  roo_spent numeric DEFAULT 0,
  sessions_count integer DEFAULT 0,
  total_time_minutes integer DEFAULT 0,
  ai_flagged_content integer DEFAULT 0,
  ai_passed_content integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_analytics_daily_pkey PRIMARY KEY (id),
  CONSTRAINT user_analytics_daily_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.user_fcm_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  token text NOT NULL,
  platform text NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_fcm_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT user_fcm_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reporter_id uuid NOT NULL,
  post_id uuid,
  comment_id uuid,
  reported_user_id uuid,
  message_id uuid,
  reason USER-DEFINED NOT NULL,
  details text,
  moderation_case_id uuid,
  processed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_reports_pkey PRIMARY KEY (id),
  CONSTRAINT user_reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES public.profiles(user_id),
  CONSTRAINT user_reports_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT user_reports_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES public.comments(id),
  CONSTRAINT user_reports_reported_user_id_fkey FOREIGN KEY (reported_user_id) REFERENCES public.profiles(user_id),
  CONSTRAINT user_reports_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.dm_messages(id),
  CONSTRAINT user_reports_moderation_case_id_fkey FOREIGN KEY (moderation_case_id) REFERENCES public.moderation_cases(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  session_token character varying NOT NULL UNIQUE,
  ip_address inet,
  user_agent text,
  device_type character varying,
  device_os character varying,
  device_browser character varying,
  browser_version character varying,
  country_code character varying,
  region character varying,
  city character varying,
  is_active boolean DEFAULT true,
  login_method character varying DEFAULT 'email'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  last_activity_at timestamp with time zone DEFAULT now(),
  ended_at timestamp with time zone,
  is_suspicious boolean DEFAULT false,
  suspicious_reason text,
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);
CREATE TABLE public.user_wallet_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  wallet_address text NOT NULL,
  encrypted_private_key text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_wallet_keys_pkey PRIMARY KEY (id),
  CONSTRAINT user_wallet_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.wallets (
  user_id uuid NOT NULL,
  balance_rc numeric NOT NULL DEFAULT 0 CHECK (balance_rc >= 0::numeric),
  pending_balance_rc numeric NOT NULL DEFAULT 0 CHECK (pending_balance_rc >= 0::numeric),
  lifetime_earned_rc numeric NOT NULL DEFAULT 0,
  lifetime_spent_rc numeric NOT NULL DEFAULT 0,
  wallet_address text NOT NULL DEFAULT encode(gen_random_bytes(16), 'hex'::text) UNIQUE,
  is_frozen boolean NOT NULL DEFAULT false,
  frozen_reason text,
  frozen_at timestamp with time zone,
  frozen_by uuid,
  daily_send_limit_rc numeric DEFAULT 10000,
  daily_sent_today_rc numeric NOT NULL DEFAULT 0,
  limit_reset_at timestamp with time zone DEFAULT (now() + '1 day'::interval),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT wallets_pkey PRIMARY KEY (user_id),
  CONSTRAINT wallets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id)
);