// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAts41-7ShsHJFNXdofJdTE2wux0gV0TPE',
    appId: '1:19404234607:web:c0f95e49dbe09c4b43129a',
    messagingSenderId: '19404234607',
    projectId: 'rooverse-production-760d4',
    authDomain: 'rooverse-production-760d4.firebaseapp.com',
    storageBucket: 'rooverse-production-760d4.firebasestorage.app',
    measurementId: 'G-EBB6BB8DR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQO3DVtRn7lU22cO7R7gXIrtLwQqjzhEw',
    appId: '1:19404234607:android:74063ed05b54833243129a',
    messagingSenderId: '19404234607',
    projectId: 'rooverse-production-760d4',
    storageBucket: 'rooverse-production-760d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRedJq5n-da-pvIdfyGrTozzgGjCneerE',
    appId: '1:19404234607:ios:42962657d6199d8043129a',
    messagingSenderId: '19404234607',
    projectId: 'rooverse-production-760d4',
    storageBucket: 'rooverse-production-760d4.firebasestorage.app',
    iosBundleId: 'com.example.rooverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRedJq5n-da-pvIdfyGrTozzgGjCneerE',
    appId: '1:19404234607:ios:42962657d6199d8043129a',
    messagingSenderId: '19404234607',
    projectId: 'rooverse-production-760d4',
    storageBucket: 'rooverse-production-760d4.firebasestorage.app',
    iosBundleId: 'com.example.rooverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAts41-7ShsHJFNXdofJdTE2wux0gV0TPE',
    appId: '1:19404234607:web:2f9bda4fcd39b3ca43129a',
    messagingSenderId: '19404234607',
    projectId: 'rooverse-production-760d4',
    authDomain: 'rooverse-production-760d4.firebaseapp.com',
    storageBucket: 'rooverse-production-760d4.firebasestorage.app',
    measurementId: 'G-VSF1T3KH7Z',
  );

}