// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBft77lb6MiCxugr4Wxncv4zwYTDjZmYc',
    appId: '1:1089008641466:web:13e28ee9a9a6c570dea983',
    messagingSenderId: '1089008641466',
    projectId: 'rooverse',
    authDomain: 'rooverse.firebaseapp.com',
    storageBucket: 'rooverse.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbhI45H-K7nxeaJxkbyimks2UtOAGFawc',
    appId: '1:1089008641466:android:2e9a3a33d165be83dea983',
    messagingSenderId: '1089008641466',
    projectId: 'rooverse',
    storageBucket: 'rooverse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiyvW-6OMBakh8hd-uP6Cw1yefdc2Junw',
    appId: '1:1089008641466:ios:9ce3d1cc6bf8236cdea983',
    messagingSenderId: '1089008641466',
    projectId: 'rooverse',
    storageBucket: 'rooverse.firebasestorage.app',
    iosBundleId: 'com.example.rooverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiyvW-6OMBakh8hd-uP6Cw1yefdc2Junw',
    appId: '1:1089008641466:ios:9ce3d1cc6bf8236cdea983',
    messagingSenderId: '1089008641466',
    projectId: 'rooverse',
    storageBucket: 'rooverse.firebasestorage.app',
    iosBundleId: 'com.example.rooverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBft77lb6MiCxugr4Wxncv4zwYTDjZmYc',
    appId: '1:1089008641466:web:aa1f8b94540a959fdea983',
    messagingSenderId: '1089008641466',
    projectId: 'rooverse',
    authDomain: 'rooverse.firebaseapp.com',
    storageBucket: 'rooverse.firebasestorage.app',
  );
}
